import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import pfp from '../public/pfp.jpg'

// components
import About from './components/About'
import Skills from './components/Skills'
import Contact from './components/Contact'

function increaseCount(count: number) {
  if (count >= 2) { return 0 }
  return count + 1
}

function decreaseCount(count: number) {
  if (count <= 0) { return 2 }
  return count - 1
}

const Home: NextPage = () => {
  const [visibleData, setVisibleData] = useState(0);

  return (
    <div>
      <Head>
        <title>Pranshu Jha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/98.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Status</h2>
            <div className={styles.pfp}>
              <Image src={pfp} alt="Pranshu's PFP" width={75} height={75} />
            </div>
            
            <p>Name: Pranshu Jha</p>
            <p>Class: Student</p>
            <p>Title: Full-Stack Developer</p>
            <hr />
            <p>Joined: Feb 2021</p>
            <p>Languages: Python, JavaScript</p>
          </div>

          <div className={styles.card}>
            <div className={styles.glitch}>
              {(() => {
                let display = visibleData ? visibleData : 0;
                switch(display) {
                  case 0:
                    return <About />
                  case 1:
                    return <Skills />
                  case 2:
                    return <Contact />
                }
              })()}
            </div>

            <div className={styles.navbar}>
              <button onClick={() => {setVisibleData(decreaseCount(visibleData))}}>&#x25C2;</button>
              <button onClick={() => {setVisibleData(increaseCount(visibleData))}}>&#x25B8;</button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
